- name: set up the vnc and shadow password for the np user
  hosts: all
  become: True
  become_user: np
  tasks:
    - debug: msg="{{ lookup('password', 'passwords/' + inventory_hostname + ' length=8 chars=abcdefghijklmnopqrstuvwxyz') }}"
      register: password
    - file: path=/home/np/.vnc state=directory
    - copy: dest=/home/np/.vnc/password.txt mode=0400 content="{{ password.msg }}\n"
    - shell: "touch /home/np/.vnc/passwd ; chmod 0600 /home/np/.vnc/passwd ; echo -n {{ password.msg }} | vncpasswd -f >/home/np/.vnc/passwd"
    - shell: mkpasswd --method=SHA-512 {{ password.msg }}
      delegate_to: 127.0.0.1
      register: crypted
      become: False
    - user: name=np password="{{crypted.stdout}}"
      become_user: root

- name: set up the authorized_keys files
  hosts: all
  vars:
    ssh_keys: |
          ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0JpU1PNFBPLNWcBaZP5wiXZcHANz0UwJgM1XtEvAcPkY772TIUlmMxxFo/HdB4qFhkKR20KyGSEPdQoEYg1DpuCDQfypI1+FAmBcqRmWO6OF7Nn87/d12KlBdDnY+Q6fgJY4YPwjdbJ3UX1mPB9fKHJMCrXFBqQ0cvN/2jG7gWKKQyElG3ZKnztwulUAK56jfgXUKuH4y/ub9lokKrNmj+aaYMZ1i+Mop4xT8e5XQs/Edz8Yt4O0jHEAA8+gRRPZQF1klDgcG+THH4By5JceKtmoFrIPqtxdi/NbtmdaG3Ry5P9/4HRJm2fW/A6tI+9RAn1t9PZWc5ImYsqV8xD2UQ== errge
          ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA1aB2DZ7gjjWs6E+uTHb5eq0LMVCeEICgGurlngUVMooKkYqyllJA7creiSSBoQ3x5EuAOmkOz7G82dHMhYJVB8ljcu80BylE2LEziCQy9t2qvK3obdWeBzQdKtk0emIgVj4+d3VLUZ2Qc2rI3r7Py6l3h82zuGgqw2NQ9Tw/rZV+97hsx0nJVu3XQiUM5LRLhwdZL166C7Yp6DT7WTj6sJC+Ul/Pm6+sGp8kXvNlZyAHhSdg5pvbct13Mi3loCEmTPST1Ll7KyWDKQev/lWV8eazKPHFNMjqoP7/28wwxGWdK/h1bZ9FciCA26rWB61uNvuPuq6cLo3Q5JqQHoTp3Q== klao
    users: [ root, np, ubuntu, errge ]
  tasks:
    - file: path=~{{ item }}/.ssh state=directory
      become: True
      become_user: "{{ item }}"
      with_items: users
    - copy:
        dest: ~{{ item }}/.ssh/authorized_keys
        mode: 0600
        content: "{{ ssh_keys }}"
      become: True
      become_user: "{{ item }}"
      with_items: users
